param()

$ErrorActionPreference = "Stop"
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)

$priorityLangs = @('fr','es','de','pt')
$articleNames = @('article-19.html','article-20.html','article-21.html','article-22.html')

$rows = New-Object "System.Collections.Generic.List[object]"

function Add-Row {
    param(
        [Parameter(Mandatory = $true)][string]$en,
        [Parameter(Mandatory = $true)][string]$fr,
        [Parameter(Mandatory = $true)][string]$es,
        [Parameter(Mandatory = $true)][string]$de,
        [Parameter(Mandatory = $true)][string]$pt
    )

    $script:rows.Add([pscustomobject]@{
        en = $en
        fr = $fr
        es = $es
        de = $de
        pt = $pt
    }) | Out-Null
}

function Apply-LocaleRows {
    param(
        [Parameter(Mandatory = $true)][string]$Content,
        [Parameter(Mandatory = $true)][string]$Lang
    )

    foreach ($row in ($rows | Sort-Object { $_.en.Length } -Descending)) {
        $replacement = $row.$Lang
        if ([string]::IsNullOrWhiteSpace($replacement)) { continue }
        $Content = $Content.Replace($row.en, $replacement)
    }

    return $Content
}

function Set-FirstRegex {
    param(
        [Parameter(Mandatory = $true)][string]$Content,
        [Parameter(Mandatory = $true)][string]$Pattern,
        [Parameter(Mandatory = $true)][string]$Replacement
    )

    return [regex]::Replace($Content, $Pattern, $Replacement, 1)
}

# ---------------------------
# Minimal but high-impact localization rows
# ---------------------------
Add-Row "Home" "Accueil" "Inicio" "Startseite" "Início"
Add-Row "Game Mode subtitles" "Sous-titres Game Mode" "Subtítulos Game Mode" "Game-Mode-Untertitel" "Legendas Game Mode"
Add-Row "Game Mode Subtitles for Fullscreen Games" "Sous-titres Game Mode pour jeux en plein écran" "Subtítulos Game Mode para juegos en pantalla completa" "Game-Mode-Untertitel für Vollbild-Spiele" "Legendas Game Mode para jogos em tela cheia"
Add-Row "When players search for <strong>game mode subtitles</strong> or <strong>subtitles for games</strong>, the real problem is usually not text quality. The issue is interaction stability: accidental overlay clicks, focus loss, and hard-to-read fast callouts in voice chat." "Quand les joueurs recherchent des <strong>sous-titres game mode</strong> ou des <strong>sous-titres pour jeux</strong>, le vrai problème n'est généralement pas la qualité du texte. Le problème est la stabilité de l'interaction : clics accidentels sur l'overlay, perte de focus et callouts vocaux rapides difficiles à lire." "Cuando los jugadores buscan <strong>subtítulos game mode</strong> o <strong>subtítulos para juegos</strong>, el problema real no suele ser la calidad del texto. El problema es la estabilidad de interacción: clics accidentales en el overlay, pérdida de foco y callouts rápidos difíciles de leer en voz." "Wenn Spieler nach <strong>Game-Mode-Untertiteln</strong> oder <strong>Untertiteln für Spiele</strong> suchen, ist das Kernproblem meist nicht die Textqualität. Es geht um Interaktionsstabilität: Fehlklicks auf dem Overlay, Fokusverlust und schwer lesbare schnelle Voice-Callouts." "Quando jogadores buscam <strong>legendas game mode</strong> ou <strong>legendas para jogos</strong>, o problema real geralmente não é a qualidade do texto. O problema é a estabilidade da interação: cliques acidentais no overlay, perda de foco e callouts rápidos difíceis de ler no chat de voz."
Add-Row "What Lock/Game Mode solves" "Ce que Lock/Game Mode résout" "Qué resuelve Lock/Game Mode" "Was Lock/Game Mode löst" "O que o Lock/Game Mode resolve"
Add-Row "Recommended setup for best visibility" "Configuration recommandée pour une visibilité maximale" "Configuración recomendada para mejor visibilidad" "Empfohlene Einrichtung für beste Sichtbarkeit" "Configuração recomendada para melhor visibilidade"
Add-Row "Where this has the most impact" "Où l'impact est le plus fort" "Dónde tiene más impacto" "Wo der größte Effekt entsteht" "Onde isso tem mais impacto"
Add-Row "Related resources" "Ressources associées" "Recursos relacionados" "Verwandte Ressourcen" "Recursos relacionados"
Add-Row "Discord and Twitch subtitles in real time" "Sous-titres Discord et Twitch en temps réel" "Subtítulos de Discord y Twitch en tiempo real" "Discord- und Twitch-Untertitel in Echtzeit" "Legendas do Discord e Twitch em tempo real"
Add-Row "Game Mode subtitles setup guide (article)" "Guide de configuration Game Mode subtitles (article)" "Guía de configuración de subtítulos Game Mode (artículo)" "Game-Mode-Untertitel Setup-Guide (Artikel)" "Guia de configuração de legendas Game Mode (artigo)"
Add-Row "Fullscreen overlay troubleshooting playbook (article)" "Playbook de diagnostic de l'overlay fullscreen (article)" "Playbook de diagnóstico del overlay fullscreen (artículo)" "Playbook zur Fehlerbehebung für Fullscreen-Overlay (Artikel)" "Playbook de diagnóstico de overlay fullscreen (artigo)"
Add-Row "Discord voice chat subtitles for international squads (article)" "Sous-titres Discord voice chat pour squads internationales (article)" "Subtítulos de Discord voice chat para squads internacionales (artículo)" "Discord-Voice-Chat-Untertitel für internationale Squads (Artikel)" "Legendas no Discord voice chat para squads internacionais (artigo)"
Add-Row "Best subtitle overlay settings for FPS and MOBA (article)" "Meilleurs réglages d'overlay de sous-titres pour FPS et MOBA (article)" "Mejores ajustes de overlay de subtítulos para FPS y MOBA (artículo)" "Beste Untertitel-Overlay-Einstellungen für FPS und MOBA (Artikel)" "Melhores configurações de overlay de legendas para FPS e MOBA (artigo)"
Add-Row "Sous-titres Game Mode setup guide (article)" "Guide de configuration des sous-titres Game Mode (article)" "Sous-titres Game Mode setup guide (article)" "Sous-titres Game Mode setup guide (article)" "Sous-titres Game Mode setup guide (article)"
Add-Row "Subtítulos Game Mode setup guide (article)" "Subtítulos Game Mode setup guide (article)" "Guía de configuración de subtítulos Game Mode (artículo)" "Subtítulos Game Mode setup guide (article)" "Subtítulos Game Mode setup guide (article)"
Add-Row "Game-Mode-Untertitel setup guide (article)" "Game-Mode-Untertitel setup guide (article)" "Game-Mode-Untertitel setup guide (article)" "Game-Mode-Untertitel-Setup-Guide (Artikel)" "Game-Mode-Untertitel setup guide (article)"
Add-Row "Legendas Game Mode setup guide (article)" "Legendas Game Mode setup guide (article)" "Legendas Game Mode setup guide (article)" "Legendas Game Mode setup guide (article)" "Guia de configuração de legendas Game Mode (artigo)"
Add-Row "Download Live Subtitles" "Télécharger Live Subtitles" "Descargar Live Subtitles" "Live Subtitles herunterladen" "Baixar Live Subtitles"
Add-Row "<h2 style=""margin-top:0;"">FAQ</h2>" "<h2 style=""margin-top:0;"">FAQ</h2>" "<h2 style=""margin-top:0;"">Preguntas frecuentes</h2>" "<h2 style=""margin-top:0;"">FAQ</h2>" "<h2 style=""margin-top:0;"">Perguntas frequentes</h2>"
Add-Row "What does Lock/Game Mode do" "Que fait Lock/Game Mode " "¿Qué hace Lock/Game Mode" "Was macht Lock/Game Mode" "O que o Lock/Game Mode faz"
Add-Row "Why are subtitles not visible in some fullscreen games" "Pourquoi les sous-titres ne sont-ils pas visibles dans certains jeux plein écran " "¿Por qué no se ven los subtítulos en algunos juegos en pantalla completa" "Warum sind Untertitel in manchen Vollbild-Spielen nicht sichtbar" "Por que as legendas não aparecem em alguns jogos em tela cheia"
Add-Row "How do I toggle quickly in a match" "Comment basculer rapidement en match " "¿Cómo alterno rápidamente durante una partida" "Wie schalte ich im Match schnell um" "Como alternar rapidamente durante a partida"
Add-Row "It keeps the overlay less intrusive during gameplay and reduces accidental interactions." "Il rend l'overlay moins intrusif pendant la partie et réduit les interactions accidentelles." "Mantiene el overlay menos intrusivo durante la partida y reduce interacciones accidentales." "Es macht das Overlay im Spiel weniger aufdringlich und reduziert versehentliche Interaktionen." "Mantém o overlay menos intrusivo durante a partida e reduz interações acidentais."
Add-Row "Some exclusive fullscreen rendering paths can hide desktop overlays. Borderless usually resolves this." "Certains modes de rendu fullscreen exclusifs peuvent masquer les overlays desktop. Le mode borderless résout généralement le problème." "Algunas rutas de renderizado fullscreen exclusivo pueden ocultar overlays de escritorio. Borderless suele resolverlo." "Einige exklusive Vollbild-Renderingpfade können Desktop-Overlays ausblenden. Borderless löst das meist." "Alguns caminhos de renderização em tela cheia exclusiva podem ocultar overlays de desktop. Borderless normalmente resolve."
Add-Row "Use Ctrl+Shift+L to turn Lock/Game Mode on or off instantly." "Utilisez Ctrl+Shift+L pour activer ou désactiver Lock/Game Mode instantanément." "Usa Ctrl+Shift+L para activar o desactivar Lock/Game Mode al instante." "Nutzen Sie Ctrl+Shift+L, um Lock/Game Mode sofort ein- oder auszuschalten." "Use Ctrl+Shift+L para ativar ou desativar Lock/Game Mode instantaneamente."

Add-Row "&larr; Back to articles" "&larr; Retour aux articles" "&larr; Volver a artículos" "&larr; Zurück zu den Artikeln" "&larr; Voltar aos artigos"
Add-Row "Core principle: stability over visual tweaks" "Principe central : la stabilité avant les retouches visuelles" "Principio clave: estabilidad por encima de ajustes visuales" "Kernprinzip: Stabilität vor visuellen Tweaks" "Princípio central: estabilidade acima de ajustes visuais"
Add-Row "Recommended baseline setup" "Configuration de base recommandée" "Configuración base recomendada" "Empfohlene Basiskonfiguration" "Configuração base recomendada"
Add-Row "Team workflow that improves callout quality" "Workflow d'équipe qui améliore la qualité des callouts" "Flujo de equipo que mejora la calidad de los callouts" "Team-Workflow zur Verbesserung der Callout-Qualität" "Fluxo de equipe que melhora a qualidade dos callouts"
Add-Row "Pre-match" "Avant le match" "Prepartida" "Vor dem Match" "Pré-partida"
Add-Row "In-match" "Pendant le match" "Durante la partida" "Im Match" "Durante a partida"
Add-Row "Post-match review" "Revue après le match" "Revisión postpartida" "Nachbesprechung" "Revisão pós-partida"
Add-Row "Visibility limits you should communicate clearly" "Limites de visibilité à communiquer clairement" "Límites de visibilidad que debes comunicar claramente" "Sichtbarkeitsgrenzen, die Sie klar kommunizieren sollten" "Limites de visibilidade que você deve comunicar com clareza"
Add-Row "KPIs worth tracking" "KPI à suivre" "KPIs que vale la pena medir" "Wichtige KPIs zur Verfolgung" "KPIs que vale acompanhar"
Add-Row "Step 1: Verify rendering mode first" "Étape 1 : vérifier d'abord le mode de rendu" "Paso 1: verifica primero el modo de renderizado" "Schritt 1: zuerst den Rendering-Modus prüfen" "Etapa 1: verifique primeiro o modo de renderização"
Add-Row "Step 2: Validate Lock/Game Mode behavior" "Étape 2 : valider le comportement Lock/Game Mode" "Paso 2: valida el comportamiento de Lock/Game Mode" "Schritt 2: Lock/Game-Mode-Verhalten validieren" "Etapa 2: valide o comportamento do Lock/Game Mode"
Add-Row "Step 3: Check subtitle layout and density" "Étape 3 : vérifier la disposition et la densité des sous-titres" "Paso 3: revisa la disposición y densidad de subtítulos" "Schritt 3: Untertitel-Layout und Dichte prüfen" "Etapa 3: verifique layout e densidade das legendas"
Add-Row "Step 4: Align team communication format" "Étape 4 : aligner le format de communication d'équipe" "Paso 4: alinea el formato de comunicación del equipo" "Schritt 4: Team-Kommunikationsformat abstimmen" "Etapa 4: alinhe o formato de comunicação da equipe"
Add-Row "Quick recovery checklist" "Checklist de récupération rapide" "Checklist de recuperación rápida" "Schnelle Recovery-Checkliste" "Checklist de recuperação rápida"
Add-Row "When escalation is required" "Quand une escalade est nécessaire" "Cuándo se requiere escalado" "Wann Eskalation erforderlich ist" "Quando é necessário escalar"
Add-Row "Baseline setup for Discord sessions" "Configuration de base pour les sessions Discord" "Configuración base para sesiones de Discord" "Basiskonfiguration für Discord-Sessions" "Configuração base para sessões no Discord"
Add-Row "Callout structure that works with subtitles" "Structure de callouts qui fonctionne avec les sous-titres" "Estructura de callouts que funciona con subtítulos" "Callout-Struktur, die mit Untertiteln funktioniert" "Estrutura de callouts que funciona com legendas"
Add-Row "Squad onboarding checklist" "Checklist d'onboarding des squads" "Checklist de onboarding del squad" "Onboarding-Checkliste für Squads" "Checklist de onboarding do squad"
Add-Row "KPIs to monitor weekly" "KPI à suivre chaque semaine" "KPIs para monitorear semanalmente" "Wöchentlich zu überwachende KPIs" "KPIs para monitorar semanalmente"
Add-Row "Placement rules" "Règles de placement" "Reglas de ubicación" "Platzierungsregeln" "Regras de posicionamento"
Add-Row "Density and formatting rules" "Règles de densité et de formatage" "Reglas de densidad y formato" "Dichte- und Formatierungsregeln" "Regras de densidade e formatação"
Add-Row "Interaction stability rules" "Règles de stabilité d'interaction" "Reglas de estabilidad de interacción" "Regeln für Interaktionsstabilität" "Regras de estabilidade de interação"
Add-Row "Preset strategy by game type" "Stratégie de preset par type de jeu" "Estrategia de preset por tipo de juego" "Preset-Strategie nach Spieltyp" "Estratégia de preset por tipo de jogo"
Add-Row "FPS preset" "Preset FPS" "Preset FPS" "FPS-Preset" "Preset FPS"
Add-Row "MOBA preset" "Preset MOBA" "Preset MOBA" "MOBA-Preset" "Preset MOBA"
Add-Row "Try the workflow in your next session" "Testez ce workflow lors de votre prochaine session" "Prueba este flujo en tu próxima sesión" "Testen Sie den Workflow in Ihrer nächsten Session" "Teste esse fluxo na sua próxima sessão"
Add-Row "Use one consistent subtitle process across games, voice chat, and streams." "Utilisez un processus de sous-titres cohérent pour les jeux, le chat vocal et les streams." "Usa un proceso de subtítulos consistente para juegos, chat de voz y streams." "Nutzen Sie einen einheitlichen Untertitel-Prozess über Spiele, Voice-Chat und Streams hinweg." "Use um processo consistente de legendas em jogos, chat de voz e streams."
Add-Row "Stabilize your overlay workflow" "Stabilisez votre workflow d'overlay" "Estabiliza tu flujo de overlay" "Stabilisieren Sie Ihren Overlay-Workflow" "Estabilize seu fluxo de overlay"
Add-Row "Use one predictable subtitle setup for games, chat, and streams." "Utilisez un seul setup de sous-titres prévisible pour les jeux, le chat et les streams." "Usa una configuración de subtítulos predecible para juegos, chat y streams." "Nutzen Sie ein vorhersehbares Untertitel-Setup für Spiele, Chat und Streams." "Use uma configuração previsível de legendas para jogos, chat e streams."
Add-Row "Standardize team communication once" "Standardisez une fois la communication d'équipe" "Estandariza la comunicación del equipo una sola vez" "Standardisieren Sie die Teamkommunikation einmalig" "Padronize a comunicação da equipe uma vez"
Add-Row "One stable subtitle workflow in Discord can improve every match day." "Un workflow de sous-titres stable sur Discord peut améliorer chaque journée de match." "Un flujo estable de subtítulos en Discord puede mejorar cada día de partidas." "Ein stabiler Untertitel-Workflow in Discord kann jeden Match-Tag verbessern." "Um fluxo estável de legendas no Discord pode melhorar cada dia de partidas."
Add-Row "Use one preset per game type" "Utilisez un preset par type de jeu" "Usa un preset por tipo de juego" "Nutzen Sie ein Preset pro Spieltyp" "Use um preset por tipo de jogo"
Add-Row "Consistency is more valuable than endless visual tweaks." "La cohérence est plus importante que des ajustements visuels sans fin." "La consistencia vale más que ajustes visuales infinitos." "Konsistenz ist wertvoller als endlose visuelle Feinanpassungen." "Consistência vale mais do que ajustes visuais sem fim."
Add-Row "Download from Microsoft Store" "Télécharger depuis Microsoft Store" "Descargar desde Microsoft Store" "Im Microsoft Store herunterladen" "Baixar na Microsoft Store"
Add-Row "Reduces accidental interaction with the subtitle overlay in matches." "Réduit les interactions accidentelles avec l'overlay de sous-titres pendant les matchs." "Reduce la interacción accidental con el overlay de subtítulos durante las partidas." "Reduziert versehentliche Interaktionen mit dem Untertitel-Overlay im Match." "Reduz interações acidentais com o overlay de legendas durante as partidas."
Add-Row "Keeps subtitle behavior stable during intense gameplay moments." "Maintient un comportement stable des sous-titres dans les moments intenses." "Mantiene estable el comportamiento de subtítulos en momentos intensos de juego." "Hält das Untertitelverhalten in intensiven Spielsituationen stabil." "Mantém o comportamento das legendas estável em momentos intensos de gameplay."
Add-Row "Improves readability for fast multilingual team callouts." "Améliore la lisibilité des callouts d'équipe multilingues et rapides." "Mejora la legibilidad de callouts rápidos y multilingües del equipo." "Verbessert die Lesbarkeit schneller mehrsprachiger Team-Callouts." "Melhora a legibilidade de callouts de equipe rápidos e multilíngues."
Add-Row "Works in the same workflow for games, Discord, and streams." "Fonctionne dans le même workflow pour les jeux, Discord et les streams." "Funciona en el mismo flujo para juegos, Discord y streams." "Funktioniert im selben Workflow pour Spiele, Discord und Streams." "Funciona no mesmo fluxo para jogos, Discord e streams."
Add-Row "Enable Lock/Game Mode before queueing." "Activez Lock/Game Mode avant de lancer la file." "Activa Lock/Game Mode antes de entrar en cola." "Aktivieren Sie Lock/Game Mode vor dem Queue-Start." "Ative Lock/Game Mode antes de entrar na fila."
Add-Row "Use <strong>Ctrl+Shift+L</strong> to toggle mode quickly." "Utilisez <strong>Ctrl+Shift+L</strong> pour basculer rapidement le mode." "Usa <strong>Ctrl+Shift+L</strong> para alternar el modo rápidamente." "Nutzen Sie <strong>Ctrl+Shift+L</strong>, um den Modus schnell umzuschalten." "Use <strong>Ctrl+Shift+L</strong> para alternar o modo rapidamente."
Add-Row "Prefer <strong>Borderless Fullscreen</strong> for stable overlay visibility." "Préférez le <strong>Borderless Fullscreen</strong> pour une visibilité stable de l'overlay." "Prefiere <strong>Borderless Fullscreen</strong> para mantener estable el overlay." "Bevorzugen Sie <strong>Borderless Fullscreen</strong> für stabile Overlay-Sichtbarkeit." "Prefira <strong>Borderless Fullscreen</strong> para manter a visibilidade do overlay estável."
Add-Row "If subtitles disappear, switch from exclusive fullscreen to borderless." "Si les sous-titres disparaissent, passez de fullscreen exclusif à borderless." "Si desaparecen los subtítulos, cambia de pantalla completa exclusiva a borderless." "Wenn Untertitel verschwinden, wechseln Sie von exklusivem Vollbild auf Borderless." "Se as legendas sumirem, troque do fullscreen exclusivo para borderless."
Add-Row "Competitive shooters, team strategy games, international squads, and stream-heavy voice communities. In these contexts, fast subtitle confirmation can reduce miscommunication and lower repeated callouts." "Shooters compétitifs, jeux d'équipe stratégiques, squads internationaux et communautés vocales orientées stream. Dans ces contextes, une confirmation rapide par sous-titres réduit les incompréhensions et les répétitions de callouts." "Shooters competitivos, juegos de estrategia en equipo, squads internacionales y comunidades de voz centradas en streams. En estos contextos, confirmar rápido con subtítulos reduce malentendidos y repeticiones de callouts." "Kompetitive Shooter, Team-Strategiespiele, internationale Squads und streamlastige Voice-Communities. In diesen Kontexten kann schnelle Untertitel-Bestätigung Missverständnisse und wiederholte Callouts reduzieren." "Shooters competitivos, jogos de estratégia em equipe, squads internacionais e comunidades de voz focadas em stream. Nesses contextos, confirmação rápida por legendas reduz falhas de comunicação e repetições de callouts."
Add-Row "Game Mode subtitles page" "Page des sous-titres Game Mode" "Página de subtítulos Game Mode" "Game-Mode-Untertitel-Seite" "Página de legendas Game Mode"
Add-Row "Discord and Twitch subtitles page" "Page des sous-titres Discord et Twitch" "Página de subtítulos de Discord y Twitch" "Discord- und Twitch-Untertitel-Seite" "Página de legendas de Discord e Twitch"
Add-Row "Game Mode setup guide for competitive games" "Guide Game Mode pour jeux compétitifs" "Guía de Game Mode para juegos competitivos" "Game-Mode-Guide für kompetitive Spiele" "Guia de Game Mode para jogos competitivos"
Add-Row "Game Mode setup guide" "Guide de configuration Game Mode" "Guía de configuración de Game Mode" "Game-Mode-Setup-Guide" "Guia de configuração Game Mode"
Add-Row "Fullscreen overlay troubleshooting playbook" "Playbook de diagnostic de l'overlay fullscreen" "Playbook de diagnóstico del overlay fullscreen" "Playbook zur Fullscreen-Overlay-Fehlerbehebung" "Playbook de diagnóstico de overlay fullscreen"
Add-Row "Fullscreen overlay troubleshooting" "Diagnostic de l'overlay fullscreen" "Diagnóstico del overlay fullscreen" "Fullscreen-Overlay-Fehlerbehebung" "Diagnóstico de overlay fullscreen"
Add-Row "Competitive setup guide" "Guide de configuration compétitive" "Guía de configuración competitiva" "Wettbewerbs-Setup-Guide" "Guia de configuração competitiva"
Add-Row "Troubleshooting playbook" "Playbook de diagnostic" "Playbook de diagnóstico" "Fehlerbehebungs-Playbook" "Playbook de diagnóstico"
Add-Row "Discord squad workflow" "Workflow Discord pour squads" "Flujo de Discord para squads" "Discord-Squad-Workflow" "Fluxo de Discord para squads"
Add-Row "Game Mode Subtitles for Competitive Games: Setup Guide 2026" "Sous-titres Game Mode pour jeux compétitifs : guide 2026" "Subtítulos Game Mode para juegos competitivos: guía 2026" "Game-Mode-Untertitel für kompetitive Spiele: Setup-Guide 2026" "Legendas Game Mode para jogos competitivos: guia de configuração 2026"
Add-Row "Fullscreen Subtitle Overlay Troubleshooting for Games" "Diagnostic de l'overlay de sous-titres fullscreen pour jeux" "Diagnóstico del overlay de subtítulos fullscreen para juegos" "Fehlerbehebung für Fullscreen-Untertitel-Overlay in Spielen" "Diagnóstico do overlay de legendas em tela cheia para jogos"
Add-Row "Discord Voice Chat Subtitles for International Squads" "Sous-titres Discord Voice Chat pour squads internationales" "Subtítulos de Discord Voice Chat para squads internacionales" "Discord-Voice-Chat-Untertitel für internationale Squads" "Legendas no Discord Voice Chat para squads internacionais"
Add-Row "Best Subtitle Overlay Settings for FPS and MOBA" "Meilleurs réglages d'overlay de sous-titres pour FPS et MOBA" "Mejores ajustes de overlay de subtítulos para FPS y MOBA" "Beste Untertitel-Overlay-Einstellungen für FPS und MOBA" "Melhores configurações de overlay de legendas para FPS e MOBA"
Add-Row "Practical setup guide for Game Mode subtitles in competitive games: lock behavior, borderless fullscreen, voice callout clarity, and team workflow." "Guide pratique de configuration des sous-titres Game Mode en compétitif : verrouillage, borderless fullscreen, clarté des callouts vocaux et workflow d'équipe." "Guía práctica de configuración de subtítulos Game Mode en competitivo: bloqueo, borderless fullscreen, claridad de callouts de voz y flujo de equipo." "Praxisleitfaden für Game-Mode-Untertitel im Wettbewerb: Lock-Verhalten, Borderless Fullscreen, klare Voice-Callouts und Team-Workflow." "Guia prático para configurar legendas Game Mode no competitivo: comportamento de bloqueio, borderless fullscreen, clareza dos callouts de voz e fluxo de equipe."
Add-Row "How to configure Lock/Game Mode for stable subtitles in competitive matches." "Comment configurer Lock/Game Mode pour des sous-titres stables en matchs compétitifs." "Cómo configurar Lock/Game Mode para subtítulos estables en partidas competitivas." "Wie man Lock/Game Mode für stabile Untertitel in kompetitiven Matches konfiguriert." "Como configurar Lock/Game Mode para legendas estáveis em partidas competitivas."
Add-Row "Practical workflow for clearer callouts and fewer subtitle overlay issues." "Workflow pratique pour des callouts plus clairs et moins de problèmes d'overlay de sous-titres." "Flujo práctico para callouts más claros y menos problemas de overlay de subtítulos." "Praktischer Workflow für klarere Callouts und weniger Untertitel-Overlay-Probleme." "Fluxo prático para callouts mais claros e menos problemas de overlay de legendas."
Add-Row "Troubleshooting checklist for subtitle overlays in games: fullscreen visibility, borderless setup, focus issues, hotkey behavior, and practical recovery steps." "Checklist de diagnostic des overlays de sous-titres en jeu : visibilité fullscreen, setup borderless, problèmes de focus, comportement des hotkeys et étapes de récupération." "Checklist de diagnóstico para overlays de subtítulos en juegos: visibilidad fullscreen, configuración borderless, problemas de foco, comportamiento de hotkeys y pasos de recuperación." "Checkliste zur Fehlerbehebung bei Untertitel-Overlays in Spielen: Fullscreen-Sichtbarkeit, Borderless-Setup, Fokusprobleme, Hotkey-Verhalten und praktische Recovery-Schritte." "Checklist de diagnóstico para overlays de legendas em jogos: visibilidade fullscreen, configuração borderless, problemas de foco, comportamento de hotkeys e passos práticos de recuperação."
Add-Row "Operational checklist to restore subtitle overlay stability in gaming scenarios." "Checklist opérationnelle pour restaurer la stabilité de l'overlay de sous-titres en contexte gaming." "Checklist operativa para restaurar la estabilidad del overlay de subtítulos en escenarios gaming." "Operative Checkliste zur Wiederherstellung der Untertitel-Overlay-Stabilität in Gaming-Szenarien." "Checklist operacional para restaurar a estabilidade do overlay de legendas em cenários de jogo."
Add-Row "Quick diagnosis path for visibility and interaction issues in game subtitle overlays." "Parcours rapide de diagnostic des problèmes de visibilité et d'interaction des overlays de sous-titres en jeu." "Ruta rápida de diagnóstico para problemas de visibilidad e interacción en overlays de subtítulos de juegos." "Schneller Diagnosepfad für Sichtbarkeits- und Interaktionsprobleme bei Untertitel-Overlays in Spielen." "Fluxo rápido de diagnóstico para problemas de visibilidade e interação em overlays de legendas de jogos."
Add-Row "Practical setup for Discord voice chat subtitles in international squads: lock mode, callout templates, and faster team coordination." "Configuration pratique des sous-titres Discord voice chat pour squads internationales : mode lock, modèles de callouts et coordination d'équipe plus rapide." "Configuración práctica de subtítulos en Discord voice chat para squads internacionales: modo lock, plantillas de callouts y coordinación de equipo más rápida." "Praktisches Setup für Discord-Voice-Chat-Untertitel in internationalen Squads: Lock-Modus, Callout-Templates und schnellere Teamkoordination." "Configuração prática de legendas no Discord voice chat para squads internacionais: modo lock, templates de callout e coordenação de equipe mais rápida."
Add-Row "How to configure subtitles in Discord voice chat for fast, multilingual team communication." "Comment configurer les sous-titres dans Discord voice chat pour une communication d'équipe multilingue et rapide." "Cómo configurar subtítulos en Discord voice chat para comunicación de equipo rápida y multilingüe." "Wie man Untertitel im Discord-Voice-Chat für schnelle, mehrsprachige Teamkommunikation konfiguriert." "Como configurar legendas no Discord voice chat para comunicação de equipe rápida e multilíngue."
Add-Row "A stable Discord subtitle workflow for squads with mixed languages and fast callouts." "Workflow de sous-titres Discord stable pour squads multilingues avec callouts rapides." "Flujo estable de subtítulos en Discord para squads multilingües con callouts rápidos." "Stabiler Discord-Untertitel-Workflow für gemischtsprachige Squads mit schnellen Callouts." "Fluxo estável de legendas no Discord para squads com idiomas mistos e callouts rápidos."
Add-Row "Best subtitle overlay settings for competitive FPS and MOBA: placement, density, contrast, and lock behavior for readable in-game communication." "Meilleurs réglages d'overlay de sous-titres pour FPS et MOBA compétitifs : position, densité, contraste et comportement lock pour une communication lisible en jeu." "Mejores ajustes de overlay de subtítulos para FPS y MOBA competitivos: posición, densidad, contraste y comportamiento de bloqueo para comunicación legible en partida." "Beste Untertitel-Overlay-Einstellungen für kompetitives FPS und MOBA: Position, Dichte, Kontrast und Lock-Verhalten für gut lesbare Kommunikation im Spiel." "Melhores configurações de overlay de legendas para FPS e MOBA competitivos: posição, densidade, contraste e comportamento de bloqueio para comunicação legível em jogo."
Add-Row "Configuration guide for readable subtitle overlays without visual distraction in ranked games." "Guide de configuration pour un overlay de sous-titres lisible sans distraction visuelle en ranked." "Guía de configuración para overlays de subtítulos legibles sin distracción visual en ranked." "Konfigurationsleitfaden für lesbare Untertitel-Overlays ohne visuelle Ablenkung in Ranked-Spielen." "Guia de configuração para overlays de legendas legíveis sem distração visual em partidas ranqueadas."
Add-Row "Practical subtitle layout standards for fast games and high-pressure voice communication." "Standards pratiques de mise en page des sous-titres pour jeux rapides et communication vocale sous pression." "Estándares prácticos de diseño de subtítulos para juegos rápidos y comunicación de voz de alta presión." "Praktische Untertitel-Layout-Standards für schnelle Spiele und Voice-Kommunikation unter Druck." "Padrões práticos de layout de legendas para jogos rápidos e comunicação de voz sob pressão."
Add-Row `
    -en 'In ranked matches, players do not lose rounds because subtitles are "bad." They lose because communication is unstable: accidental overlay interactions, unclear fast callouts, and missed context in multilingual voice chat. This guide focuses on reliable <strong>Game Mode subtitles</strong> setup.' `
    -fr "Dans les matchs classés, les équipes ne perdent pas parce que les sous-titres sont  mauvais . Elles perdent quand la communication devient instable : clics accidentels sur l'overlay, callouts rapides peu clairs et contexte manqué en chat vocal multilingue. Ce guide se concentre sur une configuration fiable des <strong>sous-titres Game Mode</strong>." `
    -es "En partidas ranked, los equipos no pierden porque los subtítulos sean malos. Pierden cuando la comunicación es inestable: interacciones accidentales con el overlay, callouts rápidos poco claros y pérdida de contexto en chat de voz multilingüe. Esta guía se centra en una configuración fiable de <strong>subtítulos Game Mode</strong>." `
    -de "In Ranked-Matches verlieren Teams nicht, weil Untertitel schlecht sind. Sie verlieren bei instabiler Kommunikation: versehentliche Overlay-Interaktionen, unklare schnelle Callouts und fehlender Kontext im mehrsprachigen Voice-Chat. Dieser Leitfaden fokussiert eine zuverlässige Einrichtung von <strong>Game-Mode-Untertiteln</strong>." `
    -pt "Em partidas ranqueadas, as equipes não perdem porque as legendas são ruins. Elas perdem quando a comunicação fica instável: interações acidentais com o overlay, callouts rápidos pouco claros e contexto perdido no chat de voz multilíngue. Este guia foca em uma configuração confiável de <strong>legendas Game Mode</strong>."
Add-Row "Font style matters less than interaction behavior. If the overlay can steal attention in a clutch moment, the system fails. Prioritize lock behavior, clear hotkey control, and predictable fullscreen rendering." "Le style de police compte moins que le comportement d'interaction. Si l'overlay peut détourner l'attention dans un clutch, le système échoue. Priorisez le verrouillage, un hotkey clair et un rendu fullscreen prévisible." "El estilo de fuente importa menos que el comportamiento de interacción. Si el overlay puede robar atención en un clutch, el sistema falla. Prioriza bloqueo, hotkey claro y renderizado fullscreen predecible." "Der Schriftstil ist weniger wichtig als das Interaktionsverhalten. Wenn das Overlay im Clutch-Moment Aufmerksamkeit abzieht, scheitert das System. Priorisieren Sie Lock-Verhalten, klare Hotkey-Steuerung und vorhersehbares Fullscreen-Rendering." "O estilo da fonte importa menos do que o comportamento de interação. Se o overlay puder roubar atenção em um clutch, o sistema falha. Priorize bloqueio, hotkey claro e renderização fullscreen previsível."
Add-Row "Enable Lock/Game Mode before entering queue." "Activez Lock/Game Mode avant d'entrer en file." "Activa Lock/Game Mode antes de entrar en cola." "Aktivieren Sie Lock/Game Mode vor dem Queue-Start." "Ative Lock/Game Mode antes de entrar na fila."
Add-Row "Use <strong>Ctrl+Shift+L</strong> as the single emergency toggle." "Utilisez <strong>Ctrl+Shift+L</strong> comme bascule d'urgence unique." "Usa <strong>Ctrl+Shift+L</strong> como único toggle de emergencia." "Nutzen Sie <strong>Ctrl+Shift+L</strong> als einzigen Notfall-Toggle." "Use <strong>Ctrl+Shift+L</strong> como único atalho de emergência."
Add-Row "Set game display mode to <strong>Borderless Fullscreen</strong>." "Réglez l'affichage du jeu sur <strong>Borderless Fullscreen</strong>." "Configura el modo de pantalla del juego en <strong>Borderless Fullscreen</strong>." "Stellen Sie den Anzeigemodus auf <strong>Borderless Fullscreen</strong>." "Defina o modo de exibição do jogo para <strong>Borderless Fullscreen</strong>."
Add-Row "Keep subtitle position fixed near your lower focal area." "Gardez la position des sous-titres fixe dans la zone basse de focalisation." "Mantén la posición de subtítulos fija en tu zona focal inferior." "Halten Sie die Untertitelposition fix im unteren Fokusbereich." "Mantenha a posição das legendas fixa na área inferior de foco."
Add-Row "Use short, high-contrast subtitle styling for peripheral reading." "Utilisez des sous-titres courts et à fort contraste pour la lecture périphérique." "Usa subtítulos cortos y de alto contraste para lectura periférica." "Nutzen Sie kurze, kontrastreiche Untertitel für peripheres Lesen." "Use estilo de legenda curto e com alto contraste para leitura periférica."
Add-Row "Align key callout vocabulary across the squad." "Alignez le vocabulaire de callouts clés dans toute l'équipe." "Alinea el vocabulario clave de callouts en todo el squad." "Stimmen Sie die wichtigsten Callout-Begriffe im Squad ab." "Alinhe o vocabulário-chave de callouts em todo o squad."
Add-Row "Define map terms and abbreviations once, then keep them stable." "Définissez les termes de map et abréviations une fois, puis gardez-les stables." "Define términos de mapa y abreviaturas una vez, y mantenlos estables." "Definieren Sie Map-Begriffe und Abkürzungen einmal und halten Sie sie konstant." "Defina termos de mapa e abreviações uma vez e mantenha-os estáveis."
Add-Row "Confirm everyone uses the same lock toggle behavior." "Vérifiez que tout le monde utilise la même logique de bascule lock." "Confirma que todos usan el mismo comportamiento de toggle lock." "Stellen Sie sicher, dass alle dasselbe Lock-Toggle-Verhalten nutzen." "Confirme que todos usam o mesmo comportamento de toggle lock."
Add-Row "Prefer short callouts: action + location + timing." "Privilégiez des callouts courts : action + position + timing." "Prefiere callouts cortos: acción + ubicación + timing." "Bevorzugen Sie kurze Callouts: Aktion + Position + Timing." "Prefira callouts curtos: ação + posição + timing."
Add-Row "Avoid long explanations during peak combat phases." "Évitez les longues explications pendant les phases de combat intense." "Evita explicaciones largas durante fases de combate intenso." "Vermeiden Sie lange Erklärungen in intensiven Kampfphasen." "Evite explicações longas durante fases de combate intenso."
Add-Row "Use subtitle confirmation for high-risk rotations." "Utilisez la confirmation par sous-titres pour les rotations à haut risque." "Usa confirmación por subtítulos para rotaciones de alto riesgo." "Nutzen Sie Untertitel-Bestätigung für riskante Rotationen." "Use confirmação por legendas para rotações de alto risco."
Add-Row "Collect 5 to 10 repeated callout patterns." "Collectez 5 à 10 patterns de callouts récurrents." "Recoge de 5 a 10 patrones de callouts repetidos." "Sammeln Sie 5 bis 10 wiederkehrende Callout-Muster." "Colete de 5 a 10 padrões de callouts repetidos."
Add-Row "Remove ambiguous phrasing that caused confusion." "Supprimez les formulations ambiguës qui ont causé de la confusion." "Elimina frases ambiguas que causaron confusión." "Entfernen Sie mehrdeutige Formulierungen, die Verwirrung ausgelöst haben." "Remova formulações ambíguas que causaram confusão."
Add-Row "Pin an updated team glossary in Discord." "Épinglez un glossaire d'équipe mis à jour sur Discord." "Fija un glosario de equipo actualizado en Discord." "Pinnen Sie ein aktualisiertes Team-Glossar in Discord." "Fixe um glossário de equipe atualizado no Discord."
Add-Row "Some exclusive fullscreen rendering paths can hide desktop overlays. This is a rendering path constraint, not always a subtitle engine bug. For operational reliability, use borderless fullscreen when possible." "Certains chemins de rendu fullscreen exclusifs peuvent masquer les overlays desktop. C'est une contrainte de rendu, pas forcément un bug du moteur de sous-titres. Pour une fiabilité opérationnelle, privilégiez le borderless fullscreen." "Algunas rutas de renderizado fullscreen exclusivo pueden ocultar overlays de escritorio. Es una limitación de renderizado, no siempre un bug del motor de subtítulos. Para fiabilidad operativa, usa borderless fullscreen siempre que sea posible." "Einige exklusive Fullscreen-Renderingpfade können Desktop-Overlays ausblenden. Das ist eine Rendering-Beschränkung und nicht immer ein Fehler der Untertitel-Engine. Für operative Zuverlässigkeit nutzen Sie nach Möglichkeit Borderless Fullscreen." "Alguns caminhos de renderização fullscreen exclusiva podem ocultar overlays de desktop. Isso é uma limitação de renderização, não necessariamente um bug do mecanismo de legendas. Para confiabilidade operacional, use borderless fullscreen sempre que possível."
Add-Row '<strong>Repeat requests:</strong> "say again" count per match.' "<strong>Demandes de répétition :</strong> nombre de  répète   par match." "<strong>Peticiones de repetición:</strong> cuántos  ¿repites  por partida." "<strong>Wiederholungsanfragen:</strong> Anzahl sag nochmal pro Match." "<strong>Pedidos de repetição:</strong> quantidade de  repete  por partida."
Add-Row "<strong>Callout latency:</strong> time from call to team response." "<strong>Latence des callouts :</strong> temps entre l'appel et la réaction de l'équipe." "<strong>Latencia de callout:</strong> tiempo entre el callout y la reacción del equipo." "<strong>Callout-Latenz:</strong> Zeit zwischen Callout und Teamreaktion." "<strong>Latência de callout:</strong> tempo do callout até a resposta da equipe."
Add-Row "<strong>Misread incidents:</strong> wrong rotation from unclear voice data." "<strong>Incidents de mauvaise lecture :</strong> rotations erronées dues à des infos vocales floues." "<strong>Incidentes de mala interpretación:</strong> rotaciones erróneas por voz poco clara." "<strong>Fehlinterpretationen:</strong> falsche Rotationen durch unklare Sprachdaten." "<strong>Incidentes de interpretação errada:</strong> rotações incorretas por dados de voz pouco claros."
Add-Row "<strong>Clutch communication quality:</strong> subjective score by IGL." "<strong>Qualité de communication en clutch :</strong> score subjectif de l'IGL." "<strong>Calidad de comunicación en clutch:</strong> puntuación subjetiva del IGL." "<strong>Kommunikationsqualität im Clutch:</strong> subjektiver Score durch den IGL." "<strong>Qualidade da comunicação em clutch:</strong> pontuação subjetiva do IGL."
Add-Row "If subtitle overlay behavior becomes unstable during gaming, random fixes usually waste time. This playbook gives a quick diagnosis order to isolate root cause: rendering mode, interaction mode, or workflow mismatch." "Si le comportement de l'overlay devient instable en jeu, les correctifs aléatoires font perdre du temps. Ce playbook donne un ordre de diagnostic rapide pour isoler la cause : mode de rendu, mode d'interaction ou décalage de workflow." "Si el comportamiento del overlay se vuelve inestable durante el juego, las soluciones aleatorias suelen perder tiempo. Este playbook da un orden de diagnóstico rápido para aislar la causa: modo de renderizado, modo de interacción o desajuste de flujo." "Wenn das Overlay-Verhalten im Spiel instabil wird, kosten Zufallsfixes meist Zeit. Dieses Playbook bietet eine schnelle Diagnose-Reihenfolge, um die Ursache zu isolieren: Rendering-Modus, Interaktionsmodus oder Workflow-Mismatch." "Se o comportamento do overlay ficar instável durante o jogo, correções aleatórias normalmente desperdiçam tempo. Este playbook traz uma ordem rápida de diagnóstico para isolar a causa: modo de renderização, modo de interação ou incompatibilidade de fluxo."
Add-Row "Before changing subtitle settings, check the game display mode. If you are in exclusive fullscreen and subtitles are missing, move to <strong>Borderless Fullscreen</strong>. This solves the majority of visibility failures for desktop overlays." "Avant de modifier les réglages, vérifiez le mode d'affichage du jeu. Si vous êtes en fullscreen exclusif et que les sous-titres manquent, passez en <strong>Borderless Fullscreen</strong>. Cela résout la majorité des problèmes de visibilité d'overlay desktop." "Antes de cambiar ajustes de subtítulos, revisa el modo de pantalla del juego. Si estás en fullscreen exclusivo y faltan subtítulos, pasa a <strong>Borderless Fullscreen</strong>. Esto resuelve la mayoría de fallos de visibilidad de overlays de escritorio." "Bevor Sie Untertitel-Einstellungen ändern, prüfen Sie den Anzeigemodus. Wenn Sie im exklusiven Vollbild sind und Untertitel fehlen, wechseln Sie auf <strong>Borderless Fullscreen</strong>. Das löst die meisten Sichtbarkeitsprobleme bei Desktop-Overlays." "Antes de alterar as configurações de legenda, verifique o modo de exibição do jogo. Se estiver em fullscreen exclusivo e as legendas sumirem, mude para <strong>Borderless Fullscreen</strong>. Isso resolve a maioria das falhas de visibilidade de overlays de desktop."
Add-Row "Toggle Lock/Game Mode on with <strong>Ctrl+Shift+L</strong>." "Activez Lock/Game Mode avec <strong>Ctrl+Shift+L</strong>." "Activa Lock/Game Mode con <strong>Ctrl+Shift+L</strong>." "Aktivieren Sie Lock/Game Mode mit <strong>Ctrl+Shift+L</strong>." "Ative Lock/Game Mode com <strong>Ctrl+Shift+L</strong>."
Add-Row "Confirm accidental clicks on the subtitle window stop happening." "Vérifiez que les clics accidentels sur la fenêtre de sous-titres cessent." "Confirma que dejan de ocurrir clics accidentales en la ventana de subtítulos." "Bestätigen Sie, dass versehentliche Klicks auf das Untertitelfenster nicht mehr auftreten." "Confirme que cliques acidentais na janela de legendas deixam de acontecer."
Add-Row "Confirm the game keeps focus during mouse movement and combat." "Vérifiez que le jeu garde le focus pendant les mouvements de souris et le combat." "Confirma que el juego mantiene el foco durante movimiento de ratón y combate." "Bestätigen Sie, dass das Spiel den Fokus bei Mausbewegung und Kampf behält." "Confirme que o jogo mantém o foco durante movimento do mouse e combate."
Add-Row "Do not overload text area. High subtitle density plus poor placement looks like a visibility bug even when rendering is fine. Use fewer lines, higher contrast, and a stable lower-screen position." "N'encombrez pas la zone de texte. Une densité élevée de sous-titres avec un mauvais placement ressemble à un bug de visibilité même si le rendu est correct. Utilisez moins de lignes, plus de contraste et une position basse stable." "No sobrecargues el área de texto. Alta densidad de subtítulos más mala ubicación parece un bug de visibilidad aunque el renderizado esté bien. Usa menos líneas, más contraste y una posición inferior estable." "Überladen Sie den Textbereich nicht. Hohe Untertiteldichte plus schlechte Platzierung wirkt wie ein Sichtbarkeitsbug, selbst wenn das Rendering korrekt ist. Nutzen Sie weniger Zeilen, höheren Kontrast und eine stabile untere Position." "Não sobrecarregue a área de texto. Alta densidade de legendas com posicionamento ruim parece bug de visibilidade, mesmo com renderização correta. Use menos linhas, maior contraste e posição inferior estável."
Add-Row 'Many "subtitle problems" are actually callout quality problems. If teammates use long sentences with inconsistent terms, subtitle usefulness drops. Standardize short callouts and shared map vocabulary.' "Beaucoup de  problèmes de sous-titres  sont en réalité des problèmes de qualité de callouts. Si les coéquipiers utilisent de longues phrases et des termes incohérents, l'utilité des sous-titres baisse. Standardisez des callouts courts et un vocabulaire map commun." "Muchos problemas de subtítulos son en realidad problemas de calidad de callouts. Si el equipo usa frases largas y términos inconsistentes, la utilidad de subtítulos baja. Estandariza callouts cortos y vocabulario común de mapa." "Viele Untertitelprobleme sind in Wahrheit Callout-Qualitätsprobleme. Wenn Teamkollegen lange Sätze mit uneinheitlichen Begriffen nutzen, sinkt der Nutzen. Standardisieren Sie kurze Callouts und gemeinsames Map-Vokabular." "Muitos problemas de legenda são, na verdade, problemas de qualidade de callout. Se o time usa frases longas e termos inconsistentes, a utilidade das legendas cai. Padronize callouts curtos e vocabulário comum de mapa."
Add-Row "Switch game to Borderless Fullscreen." "Passez le jeu en Borderless Fullscreen." "Cambia el juego a Borderless Fullscreen." "Stellen Sie das Spiel auf Borderless Fullscreen um." "Mude o jogo para Borderless Fullscreen."
Add-Row "Enable Lock/Game Mode and test Ctrl+Shift+L." "Activez Lock/Game Mode et testez Ctrl+Shift+L." "Activa Lock/Game Mode y prueba Ctrl+Shift+L." "Aktivieren Sie Lock/Game Mode und testen Sie Ctrl+Shift+L." "Ative Lock/Game Mode e teste Ctrl+Shift+L."
Add-Row "Move subtitles to stable lower-screen zone." "Déplacez les sous-titres vers une zone basse stable." "Mueve subtítulos a una zona inferior estable." "Verschieben Sie Untertitel in eine stabile untere Bildschirmzone." "Mova as legendas para uma zona inferior estável."
Add-Row "Reduce on-screen subtitle block size." "Réduisez la taille du bloc de sous-titres à l'écran." "Reduce el tamaño del bloque de subtítulos en pantalla." "Reduzieren Sie die Größe des Untertitelblocks auf dem Bildschirm." "Reduza o tamanho do bloco de legendas na tela."
Add-Row "Re-test in a live voice channel for 3 to 5 minutes." "Retestez dans un canal vocal live pendant 3 à 5 minutes." "Vuelve a probar en un canal de voz en vivo durante 3 a 5 minutos." "Testen Sie 3 bis 5 Minuten in einem Live-Voice-Channel." "Teste novamente em um canal de voz ao vivo por 3 a 5 minutos."
Add-Row "If overlay is still hidden in specific titles, document exact game, API mode, and display path. This helps separate title-specific rendering constraints from generic subtitle configuration issues." "Si l'overlay reste masqué sur certains jeux, documentez le jeu exact, le mode API et le chemin d'affichage. Cela aide à distinguer les contraintes de rendu propres au titre des problèmes de configuration génériques." "Si el overlay sigue oculto en títulos concretos, documenta juego exacto, modo API y ruta de visualización. Esto ayuda a separar limitaciones de renderizado del título de problemas genéricos de configuración." "Wenn das Overlay in bestimmten Titeln weiterhin verborgen bleibt, dokumentieren Sie genaues Spiel, API-Modus und Display-Pfad. So lassen sich titelabhängige Rendering-Beschränkungen von generischen Konfigurationsproblemen trennen." "Se o overlay continuar oculto em títulos específicos, documente jogo exato, modo de API e caminho de exibição. Isso ajuda a separar limitações de renderização do título de problemas genéricos de configuração."
Add-Row "International squads often lose rounds because callouts are not decoded fast enough. The issue is not voice quality alone. It is speed and consistency of understanding. A subtitle layer in Discord can reduce repeats and shorten reaction time when every second matters." "Les squads internationales perdent souvent des rounds parce que les callouts ne sont pas compris assez vite. Le problème n'est pas seulement la qualité audio, mais la vitesse et la constance de compréhension. Une couche de sous-titres sur Discord peut réduire les répétitions et le temps de réaction quand chaque seconde compte." "Los squads internacionales suelen perder rondas porque los callouts no se decodifican lo bastante rápido. El problema no es solo la calidad de voz, sino la velocidad y consistencia de comprensión. Una capa de subtítulos en Discord puede reducir repeticiones y acortar el tiempo de reacción cuando cada segundo cuenta." "Internationale Squads verlieren oft Runden, weil Callouts nicht schnell genug verstanden werden. Das Problem ist nicht nur Sprachqualität, sondern Geschwindigkeit und Konsistenz beim Verstehen. Eine Untertitel-Ebene in Discord kann Wiederholungen reduzieren und die Reaktionszeit verkürzen, wenn jede Sekunde zählt." "Squads internacionais frequentemente perdem rounds porque os callouts não são entendidos rápido o suficiente. O problema não é apenas qualidade de voz, mas velocidade e consistência de entendimento. Uma camada de legendas no Discord pode reduzir repetições e encurtar o tempo de reação quando cada segundo importa."
Add-Row "Enable Lock/Game Mode before joining voice channel." "Activez Lock/Game Mode avant de rejoindre le canal vocal." "Activa Lock/Game Mode antes de entrar al canal de voz." "Aktivieren Sie Lock/Game Mode vor dem Eintritt in den Voice-Channel." "Ative Lock/Game Mode antes de entrar no canal de voz."
Add-Row "Keep one hotkey for emergency toggle: <strong>Ctrl+Shift+L</strong>." "Gardez un hotkey unique pour l'urgence : <strong>Ctrl+Shift+L</strong>." "Mantén un único hotkey de emergencia: <strong>Ctrl+Shift+L</strong>." "Behalten Sie einen Notfall-Hotkey: <strong>Ctrl+Shift+L</strong>." "Mantenha um único hotkey de emergência: <strong>Ctrl+Shift+L</strong>."
Add-Row "Use borderless fullscreen in the game for overlay stability." "Utilisez le borderless fullscreen en jeu pour la stabilité de l'overlay." "Usa borderless fullscreen en el juego para estabilidad del overlay." "Nutzen Sie Borderless Fullscreen im Spiel für Overlay-Stabilität." "Use borderless fullscreen no jogo para estabilidade do overlay."
Add-Row "Set subtitle position to lower-center area with high contrast." "Placez les sous-titres en zone basse centrale avec fort contraste." "Coloca los subtítulos en la zona inferior central con alto contraste." "Positionieren Sie Untertitel unten mittig mit hohem Kontrast." "Posicione as legendas na área inferior central com alto contraste."
Add-Row "Use short format: <strong>action + location + timing</strong>." "Utilisez un format court : <strong>action + position + timing</strong>." "Usa formato corto: <strong>acción + ubicación + timing</strong>." "Nutzen Sie ein kurzes Format: <strong>Aktion + Position + Timing</strong>." "Use formato curto: <strong>ação + posição + timing</strong>."
Add-Row "Keep one term per map zone and avoid synonyms mid-match." "Conservez un terme par zone de map et évitez les synonymes en plein match." "Mantén un término por zona de mapa y evita sinónimos durante la partida." "Nutzen Sie pro Map-Zone nur einen Begriff und vermeiden Sie Synonyme im Match." "Mantenha um termo por zona do mapa e evite sinônimos durante a partida."
Add-Row "Avoid overlapping long explanations during fights." "Évitez les longues explications qui se chevauchent pendant les fights." "Evita explicaciones largas superpuestas durante peleas." "Vermeiden Sie überlappende lange Erklärungen während Kämpfen." "Evite explicações longas sobrepostas durante lutas."
Add-Row "Confirm critical calls with one-word acknowledgement." "Confirmez les calls critiques avec un accusé en un mot." "Confirma llamadas críticas con una respuesta de una palabra." "Bestätigen Sie kritische Calls mit einer Ein-Wort-Rückmeldung." "Confirme calls críticos com um reconhecimento de uma palavra."
Add-Row "Create a shared glossary of 20 to 30 map terms." "Créez un glossaire partagé de 20 à 30 termes de map." "Crea un glosario compartido de 20 a 30 términos de mapa." "Erstellen Sie ein gemeinsames Glossar mit 20 bis 30 Map-Begriffen." "Crie um glossário compartilhado com 20 a 30 termos de mapa."
Add-Row "Pin the glossary in Discord channel description." "Épinglez le glossaire dans la description du canal Discord." "Fija el glosario en la descripción del canal de Discord." "Pinnen Sie das Glossar in der Discord-Kanalbeschreibung." "Fixe o glossário na descrição do canal do Discord."
Add-Row "Run one short scrim to calibrate subtitle placement." "Faites un scrim court pour calibrer le placement des sous-titres." "Haz un scrim corto para calibrar la posición de subtítulos." "Führen Sie ein kurzes Scrim zur Kalibrierung der Untertitelposition durch." "Faça um scrim curto para calibrar o posicionamento das legendas."
Add-Row "Track repeated callout confusion and remove weak terms." "Suivez les confusions récurrentes de callouts et retirez les termes faibles." "Rastrea confusiones repetidas en callouts y elimina términos débiles." "Verfolgen Sie wiederkehrende Callout-Verwirrungen und entfernen Sie schwache Begriffe." "Rastreie confusões repetidas em callouts e remova termos fracos."
Add-Row "How often teammates ask to repeat callouts." "Fréquence à laquelle les coéquipiers demandent de répéter les callouts." "Con qué frecuencia los compañeros piden repetir callouts." "Wie oft Teammitglieder um Wiederholung von Callouts bitten." "Com que frequência os colegas pedem para repetir callouts."
Add-Row "Average delay from callout to team action." "Délai moyen entre callout et action de l'équipe." "Retraso promedio entre callout y acción del equipo." "Durchschnittliche Verzögerung von Callout bis Teamaktion." "Atraso médio entre callout e ação da equipe."
Add-Row "Mis-rotations caused by misunderstood voice comms." "Mauvaises rotations causées par des communications vocales mal comprises." "Rotaciones erróneas causadas por comunicaciones de voz mal entendidas." "Fehlrotationen durch missverstandene Sprachkommunikation." "Rotações erradas causadas por comunicação de voz mal compreendida."
Add-Row "In fast games, subtitle quality depends less on style and more on layout discipline. A readable overlay should support decisions, not compete with the HUD. This guide gives practical settings for FPS and MOBA matches." "Dans les jeux rapides, la qualité des sous-titres dépend moins du style que de la discipline de layout. Un overlay lisible doit aider la décision, pas concurrencer le HUD. Ce guide propose des réglages pratiques pour FPS et MOBA." "En juegos rápidos, la calidad de subtítulos depende menos del estilo y más de la disciplina de layout. Un overlay legible debe apoyar decisiones, no competir con el HUD. Esta guía da ajustes prácticos para partidas FPS y MOBA." "In schnellen Spielen hängt Untertitelqualität weniger vom Stil als von Layout-Disziplin ab. Ein lesbares Overlay soll Entscheidungen unterstützen, nicht mit dem HUD konkurrieren. Dieser Leitfaden liefert praktische Einstellungen für FPS- und MOBA-Matches." "Em jogos rápidos, a qualidade das legendas depende menos do estilo e mais da disciplina de layout. Um overlay legível deve apoiar decisões, não competir com o HUD. Este guia traz configurações práticas para partidas de FPS e MOBA."
Add-Row "Keep subtitles in lower-center or lower-left area, outside crosshair path." "Gardez les sous-titres en bas-centre ou bas-gauche, hors trajectoire du viseur." "Mantén subtítulos en zona inferior central o inferior izquierda, fuera de la trayectoria de la mira." "Halten Sie Untertitel unten mittig oder unten links, außerhalb der Visierlinie." "Mantenha as legendas na área inferior central ou inferior esquerda, fora do caminho da mira."
Add-Row "Avoid edges where minimap, kill feed, or ability cooldowns already compete for attention." "Évitez les zones où minimap, kill feed ou cooldowns concurrencent déjà l'attention." "Evita zonas donde minimapa, kill feed o cooldowns ya compiten por atención." "Vermeiden Sie Bereiche, in denen Minimap, Kill-Feed oder Cooldowns bereits Aufmerksamkeit beanspruchen." "Evite áreas onde minimapa, kill feed ou cooldowns já disputam atenção."
Add-Row "Do not change position mid-session unless a conflict is critical." "Ne changez pas la position en cours de session sauf conflit critique." "No cambies la posición a mitad de sesión salvo conflicto crítico." "Ändern Sie die Position während der Session nur bei kritischem Konflikt." "Não mude a posição no meio da sessão, exceto em conflito crítico."
Add-Row "Prefer 1 to 2 short lines over long wrapped paragraphs." "Préférez 1 à 2 lignes courtes aux longs paragraphes renvoyés." "Prefiere 1 a 2 líneas cortas en lugar de párrafos largos." "Bevorzugen Sie 1 bis 2 kurze Zeilen statt langer Absätze." "Prefira 1 a 2 linhas curtas em vez de parágrafos longos."
Add-Row "Use high contrast text and moderate background opacity." "Utilisez un texte à fort contraste et une opacité de fond modérée." "Usa texto de alto contraste y opacidad moderada de fondo." "Nutzen Sie hohen Textkontrast und moderate Hintergrundopazität." "Use texto de alto contraste e opacidade moderada de fundo."
Add-Row "Increase line spacing slightly for peripheral readability." "Augmentez légèrement l'interligne pour la lisibilité périphérique." "Aumenta ligeramente el interlineado para lectura periférica." "Erhöhen Sie den Zeilenabstand leicht für bessere periphere Lesbarkeit." "Aumente levemente o espaçamento entre linhas para leitura periférica."
Add-Row "Avoid decorative fonts that reduce recognition speed." "Évitez les polices décoratives qui réduisent la vitesse de reconnaissance." "Evita fuentes decorativas que reducen la velocidad de reconocimiento." "Vermeiden Sie dekorative Schriftarten, die die Erkennungsgeschwindigkeit senken." "Evite fontes decorativas que reduzem a velocidade de reconhecimento."
Add-Row "Enable Lock/Game Mode before queue start." "Activez Lock/Game Mode avant le lancement de la file." "Activa Lock/Game Mode antes de iniciar la cola." "Aktivieren Sie Lock/Game Mode vor dem Queue-Start." "Ative Lock/Game Mode antes de iniciar a fila."
Add-Row "Use Ctrl+Shift+L for immediate emergency toggle." "Utilisez Ctrl+Shift+L pour une bascule d'urgence immédiate." "Usa Ctrl+Shift+L para toggle de emergencia inmediato." "Nutzen Sie Ctrl+Shift+L für sofortiges Notfall-Toggle." "Use Ctrl+Shift+L para alternância imediata de emergência."
Add-Row "Use Borderless Fullscreen to keep desktop overlay visible." "Utilisez Borderless Fullscreen pour garder l'overlay desktop visible." "Usa Borderless Fullscreen para mantener visible el overlay de escritorio." "Nutzen Sie Borderless Fullscreen, damit das Desktop-Overlay sichtbar bleibt." "Use Borderless Fullscreen para manter o overlay de desktop visível."
Add-Row "Re-test settings after major game patch updates." "Retestez les réglages après les mises à jour majeures du jeu." "Vuelve a probar los ajustes tras parches importantes del juego." "Testen Sie die Einstellungen nach großen Spiel-Patches erneut." "Teste novamente as configurações após grandes patches do jogo."
Add-Row "Small-to-medium font, high contrast, minimal background." "Police petite à moyenne, fort contraste, fond minimal." "Fuente pequeña-media, alto contraste, fondo mínimo." "Kleine bis mittlere Schrift, hoher Kontrast, minimaler Hintergrund." "Fonte pequena a média, alto contraste, fundo mínimo."
Add-Row "Short subtitle timeout for fast combat phases." "Timeout de sous-titres court pour les phases de combat rapides." "Tiempo de subtítulo corto para fases de combate rápidas." "Kurze Untertitel-Timeouts für schnelle Kampfphasen." "Tempo curto de exibição de legendas para fases rápidas de combate."
Add-Row "Medium font, slightly longer timeout for macro calls." "Police moyenne, timeout légèrement plus long pour les macro-calls." "Fuente media, timeout algo más largo para macro-calls." "Mittlere Schrift, leicht längerer Timeout für Makro-Calls." "Fonte média, timeout um pouco maior para macro-calls."
Add-Row "Position away from minimap and objective timers." "Positionnez loin de la minimap et des timers d'objectifs." "Posiciona lejos del minimapa y temporizadores de objetivos." "Positionieren Sie weg von Minimap und Ziel-Timern." "Posicione longe do minimapa e dos temporizadores de objetivos."
Add-Row "March 5, 2026" "5 mars 2026" "5 de marzo de 2026" "5. März 2026" "5 de março de 2026"

$gameSeo = @{
    'fr' = @{
        title = 'Sous-titres Game Mode pour jeux en plein écran | Live Subtitles'
        description = 'Utilisez les sous-titres Lock/Game Mode pour les jeux plein écran, le chat vocal et les streams. Stabilisez l''overlay et réduisez les clics accidentels.'
        keywords = 'sous-titres game mode, sous-titres jeux, overlay sous-titres fullscreen, borderless fullscreen, sous-titres discord gaming'
        ogDescription = 'Lock/Game Mode aide à maintenir des sous-titres stables pendant les sessions gaming et le chat vocal.'
        twitterDescription = 'Configuration pratique des sous-titres pour jeux, streams et chat vocal rapide.'
    }
    'es' = @{
        title = 'Subtítulos Game Mode para juegos en pantalla completa | Live Subtitles'
        description = 'Usa subtítulos Lock/Game Mode para juegos en pantalla completa, chat de voz y streams. Mantén el overlay estable y reduce clics accidentales.'
        keywords = 'subtítulos game mode, subtítulos para juegos, overlay subtítulos fullscreen, borderless fullscreen, subtítulos discord gaming'
        ogDescription = 'Lock/Game Mode ayuda a mantener subtítulos estables en sesiones gaming y chat de voz.'
        twitterDescription = 'Configuración práctica de subtítulos para juegos, streams y chat de voz rápido.'
    }
    'de' = @{
        title = 'Game-Mode-Untertitel für Vollbild-Spiele | Live Subtitles'
        description = 'Nutzen Sie Lock/Game-Mode-Untertitel für Vollbild-Spiele, Voice-Chat und Streams. Halten Sie das Overlay stabil und reduzieren Sie Fehlklicks.'
        keywords = 'game-mode untertitel, untertitel für spiele, vollbild untertitel overlay, borderless fullscreen untertitel, discord gaming untertitel'
        ogDescription = 'Lock/Game Mode hält Untertitel in Gaming-Sessions und Voice-Chat stabil.'
        twitterDescription = 'Praktische Einrichtung von Untertiteln für Spiele, Streams und schnellen Voice-Chat.'
    }
    'pt' = @{
        title = 'Legendas Game Mode para jogos em tela cheia | Live Subtitles'
        description = 'Use legendas Lock/Game Mode para jogos em tela cheia, chat de voz e streams. Mantenha o overlay estável e reduza cliques acidentais.'
        keywords = 'legendas game mode, legendas para jogos, overlay de legendas fullscreen, borderless fullscreen, legendas discord gaming'
        ogDescription = 'Lock/Game Mode ajuda a manter legendas estáveis em sessões de jogo e chat de voz.'
        twitterDescription = 'Configuração prática de legendas para jogos, streams e chat de voz rápido.'
    }
}

 $sourceGamePath = Join-Path $PSScriptRoot "game-mode-subtitles.html"
if (-not (Test-Path $sourceGamePath)) {
    throw "Missing source page: $sourceGamePath"
}
$sourceGameContent = [System.IO.File]::ReadAllText($sourceGamePath, $utf8NoBom)

foreach ($lang in $priorityLangs) {
    $langDir = Join-Path $PSScriptRoot $lang
    if (-not (Test-Path $langDir)) {
        New-Item -Path $langDir -ItemType Directory | Out-Null
    }
    $gamePath = Join-Path $langDir "game-mode-subtitles.html"

    $content = $sourceGameContent
    $seo = $gameSeo[$lang]
    $url = "https://live-subtitles.com/$lang/game-mode-subtitles.html"

    $content = Set-FirstRegex -Content $content -Pattern '<html lang="[^"]+">' -Replacement "<html lang=`"$lang`">"
    $content = Set-FirstRegex -Content $content -Pattern '<title>.*</title>' -Replacement "<title>$($seo.title)</title>"
    $content = Set-FirstRegex -Content $content -Pattern '<meta name="description" content="[^"]*">' -Replacement "<meta name=`"description`" content=`"$($seo.description)`">"
    $content = Set-FirstRegex -Content $content -Pattern '<meta name="keywords" content="[^"]*">' -Replacement "<meta name=`"keywords`" content=`"$($seo.keywords)`">"
    $content = Set-FirstRegex -Content $content -Pattern '<meta name="robots" content="[^"]+">' -Replacement '<meta name="robots" content="index, follow">'
    $content = Set-FirstRegex -Content $content -Pattern '<link rel="canonical" href="[^"]+" />' -Replacement "<link rel=`"canonical`" href=`"$url`" />"
    $content = Set-FirstRegex -Content $content -Pattern '<meta property="og:title" content="[^"]*">' -Replacement "<meta property=`"og:title`" content=`"$($seo.title)`">"
    $content = Set-FirstRegex -Content $content -Pattern '<meta property="og:description" content="[^"]*">' -Replacement "<meta property=`"og:description`" content=`"$($seo.ogDescription)`">"
    $content = Set-FirstRegex -Content $content -Pattern '<meta property="og:url" content="[^"]+">' -Replacement "<meta property=`"og:url`" content=`"$url`">"
    $content = Set-FirstRegex -Content $content -Pattern '<meta name="twitter:title" content="[^"]*">' -Replacement "<meta name=`"twitter:title`" content=`"$($seo.title)`">"
    $content = Set-FirstRegex -Content $content -Pattern '<meta name="twitter:description" content="[^"]*">' -Replacement "<meta name=`"twitter:description`" content=`"$($seo.twitterDescription)`">"

    $content = $content.Replace('href="/"', "href=`"/$lang/`"")
    $content = $content.Replace('href="discord-twitch-subtitles.html"', "href=`"/$lang/discord-twitch-subtitles.html`"")
    $content = $content.Replace('href="/articles/en/article-19.html"', "href=`"/articles/$lang/article-19.html`"")
    $content = $content.Replace('href="/articles/en/article-20.html"', "href=`"/articles/$lang/article-20.html`"")
    $content = $content.Replace('href="/articles/en/article-21.html"', "href=`"/articles/$lang/article-21.html`"")
    $content = $content.Replace('href="/articles/en/article-22.html"', "href=`"/articles/$lang/article-22.html`"")

    $content = Apply-LocaleRows -Content $content -Lang $lang
    [System.IO.File]::WriteAllText($gamePath, $content, $utf8NoBom)
}

foreach ($lang in $priorityLangs) {
    $articlesDir = Join-Path $PSScriptRoot "articles\$lang"
    if (-not (Test-Path $articlesDir)) {
        New-Item -Path $articlesDir -ItemType Directory | Out-Null
    }

    foreach ($articleName in $articleNames) {
        $sourcePath = Join-Path $PSScriptRoot "articles\en\$articleName"
        if (-not (Test-Path $sourcePath)) {
            throw "Missing source article: $sourcePath"
        }

        $path = Join-Path $articlesDir $articleName
        $content = [System.IO.File]::ReadAllText($sourcePath, $utf8NoBom)
        $url = "https://live-subtitles.com/articles/$lang/$articleName"

        $content = Set-FirstRegex -Content $content -Pattern '<html lang="[^"]+">' -Replacement "<html lang=`"$lang`">"
        $content = Set-FirstRegex -Content $content -Pattern '<meta name="robots" content="[^"]+">' -Replacement '<meta name="robots" content="index, follow">'
        $content = Set-FirstRegex -Content $content -Pattern '<link rel="canonical" href="[^"]+" />' -Replacement "<link rel=`"canonical`" href=`"$url`" />"
        $content = Set-FirstRegex -Content $content -Pattern '<meta property="og:url" content="[^"]+">' -Replacement "<meta property=`"og:url`" content=`"$url`">"
        $content = Set-FirstRegex -Content $content -Pattern '"mainEntityOfPage": "[^"]+"' -Replacement "`"mainEntityOfPage`": `"$url`""

        $content = $content.Replace('href="/game-mode-subtitles.html"', "href=`"/$lang/game-mode-subtitles.html`"")
        $content = $content.Replace('href="/discord-twitch-subtitles.html"', "href=`"/$lang/discord-twitch-subtitles.html`"")

        $content = Apply-LocaleRows -Content $content -Lang $lang
        [System.IO.File]::WriteAllText($path, $content, $utf8NoBom)
    }
}

Write-Host "Localized priority game cluster (fr/es/de/pt): indexability + core body translation + self-canonical."
